/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.car_rental.Screens;

import com.mycompany.car_rental.ConnectionClass.ConnectionClass;
import constants.Values;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.UserModel;

/**
 *
 * @author SONY VIAO
 */
public class BillingScreen extends javax.swing.JFrame implements Values{

    private final UserModel currentUser;

    /**
     * Creates new form BillingScreen
     */
    public BillingScreen(UserModel currentUser) {
        this.currentUser=currentUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        vehiclesInternalFrame = new javax.swing.JInternalFrame();
        vehicleTableScrollPane = new javax.swing.JScrollPane();
        vehiclesTable = new javax.swing.JTable();
        optionPanel = new javax.swing.JPanel();
        vehicleButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehiclesInternalFrame.setBorder(null);
        vehiclesInternalFrame.setVisible(true);
        vehiclesInternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        vehicleTableScrollPane.setViewportView(vehiclesTable);

        vehiclesInternalFrame.getContentPane().add(vehicleTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 450));

        tabbedPane.addTab("Vehicles", vehiclesInternalFrame);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -100, -1, -1));

        optionPanel.setBackground(new java.awt.Color(153, 153, 153));
        optionPanel.setPreferredSize(new java.awt.Dimension(150, 450));
        optionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicleButton.setText("Vehicles");
        vehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleButtonActionPerformed(evt);
            }
        });
        optionPanel.add(vehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, -1));

        goBackButton.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        goBackButton.setText("GO BACK");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        optionPanel.add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("BILLING");
        optionPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        getContentPane().add(optionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleButtonActionPerformed
        updateVehiclesTable();
        tabbedPane.setSelectedComponent(vehiclesInternalFrame);
    }//GEN-LAST:event_vehicleButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        if(currentUser.getRole()==ADMIN_ROLE){
            new AdminDashBoard(currentUser).setVisible(true);   
        }else if(currentUser.getRole()==MANAGER_ROLE){
            new ManagerDashBoard(currentUser).setVisible(true);   
        }
        dispose(); 
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void updateVehiclesTable(){
    
        final String statement = "SELECT * from vehicles";
        try {
            PreparedStatement preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(statement);

            ResultSet resultSet = preparedStatement.executeQuery();
            
            final String[] headerName = {"ID","Model", "Number","Max Seats","Rent/Day","On Rent"};
            DefaultTableModel model = new DefaultTableModel(null, headerName);
            vehiclesTable.setModel(model);
            Object[] row = new Object[6];

            while (resultSet.next()) {
                row[0] = resultSet.getString("id");
                row[1] = resultSet.getString("model");
                row[2] = resultSet.getString("number");
                row[3] = resultSet.getInt("max_seats");
                row[4] = resultSet.getInt("rent_per_day");
                row[5] = resultSet.getInt("is_rented");
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JButton vehicleButton;
    private javax.swing.JScrollPane vehicleTableScrollPane;
    private javax.swing.JInternalFrame vehiclesInternalFrame;
    private javax.swing.JTable vehiclesTable;
    // End of variables declaration//GEN-END:variables
}
