/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.car_rental.Screens;

/**
 *
 * @author SONY VIAO
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashPanel = new javax.swing.JPanel();
        percentageLabel = new javax.swing.JLabel();
        splashLoading = new javax.swing.JProgressBar();
        loadingTextLabel = new javax.swing.JLabel();
        splashIcon = new javax.swing.JLabel();
        walkingAnimation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(800, 450));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        splashPanel.setBackground(new java.awt.Color(255, 255, 255));
        splashPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        splashPanel.setMaximumSize(new java.awt.Dimension(800, 450));
        splashPanel.setMinimumSize(new java.awt.Dimension(800, 450));
        splashPanel.setPreferredSize(new java.awt.Dimension(800, 450));
        splashPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        percentageLabel.setBackground(new java.awt.Color(204, 204, 204));
        percentageLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        percentageLabel.setText("0%");
        splashPanel.add(percentageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 50, 20));

        splashLoading.setForeground(new java.awt.Color(0, 102, 204));
        splashLoading.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        splashPanel.add(splashLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 800, 20));

        loadingTextLabel.setForeground(new java.awt.Color(102, 102, 102));
        loadingTextLabel.setText("Loading....");
        splashPanel.add(loadingTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        splashIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CarRentalIcon.png"))); // NOI18N
        splashPanel.add(splashIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 600, 370));

        walkingAnimation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile000.png"))); // NOI18N
        splashPanel.add(walkingAnimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, 50));

        getContentPane().add(splashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     
        /* display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                screen.setVisible(true);
            }
        });
        
         try{
            
            for(int i=1;i<=100;i++){
                
                Thread.sleep(35);
                screen.splashLoading.setValue(i);
                screen.percentageLabel.setText(""+i+"%");
                setAnimationIcon(i);
                if(i==60){
                    screen.loadingTextLabel.setText("Almost Done!!");
                }else if(i==80){
                    screen.loadingTextLabel.setText("Opening...."); 
                }
            }
            
        }catch(Exception e){
            
        }
        new LoginPage().setVisible(true);
        screen.dispose();
        
    }

    
    private static void setAnimationIcon(int i) {
        if(i%16==1){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile000.png")));
        }
        if(i%16==3){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile001.png")));
        }
        if(i%16==5){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile002.png")));
        }
        if(i%16==6){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile003.png")));
        }
        if(i%16==9){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile004.png")));
        }
        if(i%16==11){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile005.png")));
        }
        if(i%16==13){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile006.png")));
        }
        if(i%16==15){
            screen.walkingAnimation.setIcon(new javax.swing.ImageIcon(screen.getClass().getResource("/images/tile007.png")));
        }
    }
    
    private static SplashScreen screen=new SplashScreen();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadingTextLabel;
    private javax.swing.JLabel percentageLabel;
    private javax.swing.JLabel splashIcon;
    private javax.swing.JProgressBar splashLoading;
    private javax.swing.JPanel splashPanel;
    private javax.swing.JLabel walkingAnimation;
    // End of variables declaration//GEN-END:variables
}
